# AUXILIARIES
# Plain auxiliaries with pronominal subject
xpos=/(APST|ANEGPST|AOPT|ANEGOPT|AAOR|ANEGAOR|AJUS|APREC)/&text=/(.*)/;xpos=/PPERS/&text=/(.*)/&morph=/.*Number.(Plur|Sing).*Person.([123]).*/&func=/nsubj/;text=/(.*)/	#1.#2;#3>#2	#1:misc,=MT=$1-$2-$3-$5-$4-$6
# Plain auxiliaries with noun subject
xpos=/(APST|ACOND|ANEGPST|AOPT|ANEGOPT|AAOR|ANEGAOR)/&text=/(.*)/;func=/nsubj/&xpos!=/PPERS/&text=/(.*)/;text=/(.*)/	#1.*#2;#3>#2;#3>#1	#1:misc,=MT=N_$1-$2-$3-$4
# Fused conditional and optative
xpos=/(AOPT_PPERS|ACOND_PPERS)/&text=/(.*)/&morph=/.*Number.(Plur|Sing).*Person.([123]).*/&func=/nsubj/;text=/(.*)/	#2>#1	#1:misc,=MT=$1-$2-$4-$3-$5
# Causative
xpos=/(ACAUS)/&text=/(.*)/;xpos=/PPERS/&text=/(.*)/&lemma=/(.*)/;xpos=/V/&text=/(.*)/	#1.#2.#3	#1:misc,=MT=$1-$2-$3-$4-$5

# FUT and Counterfactual
xpos=/(FUT)/&text=/(.*)/;xpos=/CPRET/&text=/(.*)/;text=/(.*)/	#3>#2;#3>#1	#1:misc,=MT=Counter_$1-$2-$3-$4;#1:storage=counterfact
xpos=/(FUT)/&text=/(.*)/&storage!=/counterfact/;text=/(.*)/;func=/nsubj/&xpos=/PPERS/&text=/(.*)/&lemma=/(.*)/	#2>#1;#2>#3	#1:misc,=MT=$1_pron-$2-$3-$4-$5;#1:storage=pron
xpos=/(FUT)/&text=/(.*)/&storage!=/.*(counterfact|pron).*/;text=/(.*)/	#2>#1	#1:misc,=MT=$1-$2-$3

# VOICE
# Stative
xpos=/(VSTAT)/&text=/(.*)/&lemma=/(.*)/&lemma!=/ⲉⲓⲣⲉ/;func=/nsubj/&text=/(.*)/	#1>#2	#1:misc,=MT=$1-$2-$3-$4
xpos=/(VSTAT)/&text=/(.*)/&lemma=/(.*)/&lemma=/ⲉⲓⲣⲉ/;func=/nsubj/&text=/(.*)/;func=/xcomp/&text=/(.*)/	#1>#2;#1>#3	#1:misc,=MT=$1O-$2-$3-$4-$5

# Relatives
xpos=/ART/&text=/(.*)/&morph=/.*Gender.(Fem|Masc).*/;xpos=/CREL/&text=/(.*)/	#1.#2	#1:misc,=MT=PET-$1-$2-$3
xpos=/ART/&text=/(.*)/&morph=/.*Number.(Plur).*/;xpos=/CREL/&text=/(.*)/	#1.#2	#1:misc,=MT=NET-$1-$2-$3

# dislocated
text=/(.*)/;func=/dislocated/&text=/(.*)/;text=/(ⲛϭⲓ|ⲛϫⲉ)/;func=/nsubj/&text=/(.*)/&xpos=/PPERS/&morph=/.*Number.(Plur|Sing).*Person.([123]).*/	#1>#2>#3;#1>#4	#3:misc,=MT=NQI-$1-$2-$3-$4-$5-$6;#2:storage=nqi
text=/(.*)/;func=/dislocated/&text=/(.*)/&storage!=/nqi/	#1>#2	#2:misc,=MT=DISLOC-$1-$2

# negation
text=/(.*)/&lemma=/ⲛ/&xpos=/NEG/;text=/(.*)/&lemma=/ⲁⲛ/&xpos=/NEG/;text=/(.*)/	#3>#2;#3>#1	#1:misc,=MT=DBLNEG-$1-$2-$3

# imperative
morph=/.*Mood.Imp.*/&text=/(.*)/	none	#1:misc,=MT=IMPER-$1

# plural
morph=/.*Number.Plur.*/&func=/det|nmod:poss/&text=/(.*)/;xpos=/N/&text=/(.*)/	#1.#2	#2:misc,=MT=PLUR-$1-$2

# expletive object 's' + ccomp
text=/(.*)/;xpos=/PPERO/&text=/(.*)/&lemma=/ⲛⲧⲟⲥ/;text=/(.*)/&func=/ccomp/;text=/(ϫⲉ)/;text=/ⲙⲙⲟ/	#1>#2;#1>#3>#4;#5.#2	#1:misc,=MT=MMOS-$1-$2-$3-$4;#1:storage=mmos
text=/(.*)/&storage!=/mmos/;xpos=/PPERO/&text=/(.*)/&lemma=/ⲛⲧⲟⲥ/;text=/(.*)/&func=/ccomp/;text=/(ϫⲉ)/	#1>#2;#1>#3>#4	#1:misc,=MT=JOOS-$1-$2-$3-$4

# ⲛⲁⲉⲓⲁⲧ, ⲁϩⲣⲟ
text=/ⲛⲁⲉⲓⲁⲧ/;func=/nsubj/&text=/(.*)/&lemma=/(.*)/	#1>#2	#1:misc,=MT=NAEIAT-$1-$2
text=/ⲁϩⲣⲟ/;xpos=/PPERS/&text=/(.*)/&lemma=/(.*)/	#1.#2	#1:misc,=MT=AHRO-$1-$2

# Names
xpos=/NPROP/&lemma=/(.*)/	none	#1:misc,=MT=NAME-$1

# Morph MSeg
text=/(.*)/&misc=/.*MSeg=(ⲙ[ⲛⲉ]ⲧ%ⲣⲉϥ%)(.*)/	none	#1:misc,=MT=MNTREF-$1-$2-$3;#1:misc-=MSeg
text=/(.*)/&misc=/.*MSeg=(ⲙ[ⲛⲉ]ⲧ%ⲁⲧ%)(.*)/	none	#1:misc,=MT=MNTAT-$1-$2-$3;#1:misc-=MSeg
text=/(.*)/&misc=/.*MSeg=(ⲙ[ⲛⲉ]ⲧ%)(.*)/&lemma!=/ⲙⲛⲧⲥⲛⲟⲟⲩⲥ/	none	#1:misc,=MT=MNT-$1-$2-$3
text=/(.*)/&misc=/.*MSeg=(ⲣⲉϥ%)(.*)/	none	#1:misc,=MT=REF-$1-$2-$3
text=/(.*)/&misc=/.*MSeg=(ⲁⲧ%)(.*)/	none	#1:misc,=MT=AT-$1-$2-$3