[dependency]
dependency.enabled=False

[conllu]
conllu.enabled=False

[constructions]
constructions.enabled=False

[lexicon]
lexicon.enabled=True
entry_langs=en
max_entries=100
max_senses_per_entry=10
dedup_senses=False
# Not Implemented
pos_tags=all
grammatical_info=False,

